@startuml
actor server
participant TrenoDirector
participant TrenoBusinessBuilder

server -> TrenoDirector : costruisciTrenoBusiness("TRENOBUS123")
activate TrenoDirector

TrenoDirector -> TrenoBusinessBuilder : setCodice("TRENOBUS123")
activate TrenoBusinessBuilder
TrenoBusinessBuilder --> TrenoBusinessBuilder : buildTipo()
TrenoBusinessBuilder --> TrenoBusinessBuilder : buildPosti()
TrenoBusinessBuilder --> TrenoBusinessBuilder : buildServizi()
TrenoBusinessBuilder --> TrenoBusinessBuilder : /* mantiene stato interno */

TrenoBusinessBuilder --> TrenoDirector : getResult() : Treno
deactivate TrenoBusinessBuilder

TrenoDirector --> server : Treno
deactivate TrenoDirector
@enduml